# Generated by Django 4.2.16 on 2024-11-19 04:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=9, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Rut invalido: Si su rut termina en "K", debe reemplazarlo con un cero "0".', regex='^[0-9]{8,9}$')])),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Ingrese un correo electrónico válido')])),
                ('contrasena', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(128), django.core.validators.RegexValidator(message='La contraseña debe tener entre 6 y 40 caracteres, con al menos una mayúscula, una minúscula, un número y un símbolo permitido (-, _, ., *).', regex='^(?=.*[a-z])(?=.*[A-Z])(?=.*[-_.*])(?=.*\\d).{6,128}$')])),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('rango', models.CharField(choices=[('f', 'Frecuente'), ('n', 'Nuevo'), ('v', 'VIP')], default='n', max_length=1)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('rut', models.CharField(max_length=9, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Rut invalido: Si su rut termina en "K", debe reemplazarlo con un cero "0".', regex='^[0-9]{8,9}$')])),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Ingrese un correo electrónico válido')])),
                ('contrasena', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(128), django.core.validators.RegexValidator(message='La contraseña debe tener entre 6 y 40 caracteres, con al menos una mayúscula, una minúscula, un número y un símbolo permitido (-, _, ., *).', regex='^(?=.*[a-z])(?=.*[A-Z])(?=.*[-_.*])(?=.*\\d).{6,128}$')])),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('cargo', models.CharField(choices=[('basico', 'Basico'), ('medio', 'Medio'), ('premium', 'Premium')], default='basico', max_length=10)),
                ('salario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
    ]
