# Generated by Django 4.2.16 on 2024-11-19 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicio', '__first__'),
        ('inicio', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('disponible', models.BooleanField(default=True)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('vehiculo', models.CharField(choices=[('c', 'City Car'), ('h', 'Hatchback/Sedán'), ('j', 'Suv/Jeep'), ('xl', 'Camionetas XL')], default='c', max_length=2)),
                ('estado_reserva', models.CharField(choices=[('p', 'Pendiente'), ('c', 'Confirmada')], default='p', max_length=2)),
                ('id_agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.agenda')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.cliente')),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_abonado', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('parcial', 'Parcial')], default='pendiente', max_length=10)),
                ('banco', models.CharField(choices=[('banco BICE', 'Banco BICE'), ('banco Chile', 'Banco Chile - Edwards/Citi'), ('banco consorcio', 'Banco Consorcio'), ('banco estado', 'Banco Estado'), ('banco falabella', 'Banco Falabella'), ('banco HSBC', 'Banco HSBC'), ('banco internacional', 'Banco Internacional'), ('banco itau', 'Banco Itaú'), ('banco Security', 'Banco Security'), ('bci', 'Banco BCI'), ('santander', 'Banco Santander'), ('scotiabank', 'Banco Scotiabank'), ('otro', 'Otro')], max_length=50)),
                ('numero_transaccion', models.CharField(max_length=100)),
                ('fecha', models.DateField(auto_now=True)),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.reserva')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.servicio')),
            ],
        ),
    ]
