# Generated by Django 4.2.16 on 2024-11-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='monto_abonado',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
