# Generated by Django 4.2.16 on 2024-11-19 04:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inicio', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('modalidad_servicio', models.CharField(choices=[('Taller', 'Taller'), ('Domicilio', 'Domicilio')], default='Taller', max_length=10)),
                ('valor', models.CharField(max_length=20)),
                ('duracion', models.DurationField(default=datetime.timedelta(seconds=3600))),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_categoria', models.CharField(choices=[('basico', 'Básico'), ('medio', 'Medio'), ('premium', 'Premium')], default='basico', max_length=10)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.empleado')),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.servicio')),
            ],
        ),
    ]
